#Starting a new workflow
name: CI

on: 
    push:
        branches: [ master ]

    workflow_dispatch:
    
jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup do NodeJS
              uses: actions/setup-node@v3.0.0
              with:
                node-version: 16.13.2
            
            - name: Instalacao do Mocha e dos pacotes para teste
              run: |
                  cd src;
                  npm install -g mocha;
                  npm install

            - name: Execucao do teste
              run: mocha src/test/convert.js

            - name: Login no DockerHub
              uses: docker/login-action@v3.3.0
              with:
                  username: ${{secrets.DOCKERHUB_USERNAME}}
                  password: ${{secrets.DOCKERHUB_PASSWORD}}
                  
            - name: Construcao da imagem docker
              uses: docker/build-push-action@v6.10.0
              with:
                  context: ./src
                  file: ./src/Dockerfile
                  push: true
                  tags: |
                      fredon99/conversao-temperatura:latest
